test
  123
  check equal to 123
  is equal to quote check yes 123

test
  123
  check equal to 124
  is equal to quote check no 123

test
  123
  check less than 124
  is equal to quote check yes 123

test
  123
  check less than 123
  is equal to quote check no 123

test
  123
  check not less than 124
  is equal to quote check no 123

test
  123
  check not less than 123
  is equal to quote check yes 123
