comment
  get is not a keyword
  details
    it gives
      the field of the current value
      with the given name
    the value
      must be a structure
      so it needs to have a single line

test
  point
    x 10
    y 20
  x
  is equal to x 10

test
  point
    x 10
    y 20
  y
  is equal to y 20

test
  circle
    radius 10
    center point
      x 20
      y 30
  center.point.x.number
  is equal to 20
