use library number

test
  2
  plus 3
  is equal 5

test
  5
  minus 3
  is equal 2

test
  2
  times 3
  is equal 6

test
  4
  is less than 5

test
  5
  is not less than 5

test
  6
  is not less than 5

test
  pi.number
  is less than 4

test
  pi.number
  is not less than 3

test
  0.sinus
  is equal 0
 
test
  0.cosinus
  is equal 1

test
  25.root
  is equal 5

test
  123.text
  is equal "123"
