test
  2
  plus 3
  is equal to 5

test
  5
  minus 3
  is equal to 2

test
  2
  times 3
  is equal to 6

test
  10
  divided by 5
  is equal to 2

comment
  implement parser for
    number inifinity
    number minus infinity
    number none
  and uncomment the tests below

comment
  test
    10
    divided by 0
    is equal to number infinity

  test
    -10
    divided by 0
    is equal to number minus infinity

  test
    0
    divided by 0
    is equal to number none

test
  4
  is less than 5

test
  5
  is not less than 5

test
  6
  is not less than 5

test
  pi.number
  is less than 4

test
  pi.number
  is not less than 3

test
  0.sinus
  is equal to 0
 
test
  0.cosinus
  is equal to 1

test
  25.root
  is equal to 5

test
  123.text
  is equal to "123"
