comment
  the
    the following word
    is treated as a word
    and not a syntactic form
  details
    it is an escape word for syntax
    like escape character for text is "/"

test
  the do 123.text
  is equal to quote do "123"

test
  the doing 123.text
  is equal to quote doing "123"

test
  the the 123.text
  is equal to quote the "123"

test
  the foo 123.text
  is equal to quote foo "123"


comment cover all syntax keywords