package leo.natives

val argsName = "args"
val arrayName = "array"
val className = "class"
val elementName = "element"
val falseName = "false"
val fieldName = "field"
val getName = "get"
val invokeName = "invoke"
val integerName = "integer"
val javaName = "java"
val methodName = "method"
val nameName = "name"
val nullName = "null"
val objectName = "object"
val trueName = "true"
val typesName = "types"

val appendName = "append"
val byName = "by"
val dividedName = "divided"
val plusName = "plus"
val minusName = "minus"
val timesName = "times"
val lessName = "less"
val thanName = "than"